baseURL = "https://fr.shoogle.net/alsace"
languageCode = "fr"
title = "Alsace"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "alsace"

[taxonomies]
  shop = "shops"
